### ISSUE TITLE
 Tensorflow 1 is unsupported error

### ISSUE THREAD

**Issue by kotaxyz** [Emotional-Text-to-Speech/dl-for-emo-tts#4]
hello there i was trying to make this runs on colab but it seems that it need update i get this error

Tensorflow 1 is unsupported in Colab.
Your notebook should be updated to use Tensorflow 2

**Comment by justachetan** [comment]
Hi, yes this is indeed a breaking change. The error arises due to some tensorflow code in https://github.com/r9y9/tacotron_pytorch 

We don't have the bandwidth to fix this right now and are as such no longer actively maintaining this repository. Feel free to clone and use it on your local machine with TF 1.0.

We are open to accepting pull requests to fix this issue for Colab tool.
